import {
	Box,
	Table,
	TableBody,
	TableCell,
	TableContainer,
	TableHead,
	TableRow,
	TablePagination,
	Paper,
	Typography,
} from "@mui/material";
import { useState } from "react";

const mockData = [
	{
		provider: "Clear Ballot",
		model: "ClearCast",
		quantity: 590,
		age: 2,
		os: "Embedded Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "91%",
		errorRate: "0.72%",
		reliability: "82%",
		qualityMeasure: "90%",
	},
	{
		provider: "Clear Ballot",
		model: "ClearAccess",
		quantity: 1515,
		age: 6,
		os: "Windows 8.1 Pro",
		certification: "VVSG 2.0 certified",
		scanRate: "62%",
		errorRate: "1.86%",
		reliability: "83%",
		qualityMeasure: "81%",
	},
	{
		provider: "Clear Ballot",
		model: "ClearCount",
		quantity: 425,
		age: 4,
		os: "Windows 7",
		certification: "Not Certified",
		scanRate: "77%",
		errorRate: "0.94%",
		reliability: "81%",
		qualityMeasure: "81%",
	},
	{
		provider: "ES&S",
		model: "DS850",
		quantity: 1672,
		age: 4,
		os: "Windows",
		certification: "VVSG 1.0 certified",
		scanRate: "94%",
		errorRate: "0.66%",
		reliability: "80%",
		qualityMeasure: "81%",
	},
	{
		provider: "ES&S",
		model: "DS450",
		quantity: 475,
		age: 6,
		os: "Windows",
		certification: "VVSG 2.0 applied",
		scanRate: "88%",
		errorRate: "1.68%",
		reliability: "80%",
		qualityMeasure: "85%",
	},
	{
		provider: "ES&S",
		model: "DS200",
		quantity: 1674,
		age: 8,
		os: "Windows",
		certification: "VVSG 2.0 applied",
		scanRate: "71%",
		errorRate: "1.57%",
		reliability: "84%",
		qualityMeasure: "82%",
	},
	{
		provider: "ES&S",
		model: "DS300",
		quantity: 691,
		age: 8,
		os: "Windows",
		certification: "VVSG 2.0 certified",
		scanRate: "53%",
		errorRate: "0.94%",
		reliability: "88%",
		qualityMeasure: "82%",
	},
	{
		provider: "ES&S",
		model: "AutoMARK",
		quantity: 660,
		age: 2,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "71%",
		errorRate: "1.17%",
		reliability: "83%",
		qualityMeasure: "88%",
	},
	{
		provider: "ES&S",
		model: "ExpressVote XL",
		quantity: 1226,
		age: 4,
		os: "Windows",
		certification: "VVSG 1.0 certified",
		scanRate: "62%",
		errorRate: "0.87%",
		reliability: "88%",
		qualityMeasure: "82%",
	},
	{
		provider: "ES&S",
		model: "ExpressTouch",
		quantity: 756,
		age: 2,
		os: "Windows",
		certification: "VVSG 1.1 certified",
		scanRate: "55%",
		errorRate: "1.12%",
		reliability: "84%",
		qualityMeasure: "90%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Precinct",
		quantity: 1331,
		age: 8,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "86%",
		errorRate: "1.44%",
		reliability: "90%",
		qualityMeasure: "87%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Precinct 2",
		quantity: 713,
		age: 1,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "82%",
		errorRate: "1.41%",
		reliability: "88%",
		qualityMeasure: "82%",
	},
	{
		provider: "Dominion",
		model: "ImageCast DRE",
		quantity: 1203,
		age: 3,
		os: "Windows",
		certification: "VVSG 1.1 certified",
		scanRate: "71%",
		errorRate: "0.87%",
		reliability: "88%",
		qualityMeasure: "81%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Evolution",
		quantity: 2135,
		age: 2,
		os: "Windows",
		certification: "VVSG 1.0 certified",
		scanRate: "98%",
		errorRate: "1.60%",
		reliability: "83%",
		qualityMeasure: "83%",
	},
	{
		provider: "ES&S",
		model: "ExpressVote",
		quantity: 1163,
		age: 1,
		os: "Windows",
		certification: "Not Certified",
		scanRate: "59%",
		errorRate: "0.25%",
		reliability: "86%",
		qualityMeasure: "80%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Central",
		quantity: 1612,
		age: 4,
		os: "Windows",
		certification: "VVSG 1.1 certified",
		scanRate: "67%",
		errorRate: "0.20%",
		reliability: "87%",
		qualityMeasure: "83%",
	},
	{
		provider: "Dominion",
		model: "ImageCast X",
		quantity: 934,
		age: 7,
		os: "Android",
		certification: "VVSG 2.0 certified",
		scanRate: "59%",
		errorRate: "0.13%",
		reliability: "88%",
		qualityMeasure: "81%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Remote",
		quantity: 1633,
		age: 8,
		os: "Web-based",
		certification: "Not Certified",
		scanRate: "73%",
		errorRate: "0.97%",
		reliability: "82%",
		qualityMeasure: "86%",
	},
	{
		provider: "ES&S",
		model: "iVotronic",
		quantity: 517,
		age: 5,
		os: "Embedded Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "100%",
		errorRate: "1.56%",
		reliability: "84%",
		qualityMeasure: "85%",
	},
	{
		provider: "ES&S",
		model: "ExpressPoll",
		quantity: 1202,
		age: 4,
		os: "Windows 10 / Windows 11",
		certification: "VVSG 2.0 certified",
		scanRate: "77%",
		errorRate: "1.74%",
		reliability: "84%",
		qualityMeasure: "86%",
	},
	{
		provider: "ES&S",
		model: "Model 100",
		quantity: 1485,
		age: 8,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "79%",
		errorRate: "0.66%",
		reliability: "85%",
		qualityMeasure: "89%",
	},
	{
		provider: "Enhanced Voting",
		model: "Enhanced Ballot",
		quantity: 316,
		age: 8,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "74%",
		errorRate: "1.51%",
		reliability: "88%",
		qualityMeasure: "82%",
	},
	{
		provider: "KNOWiNK",
		model: "Poll Pad",
		quantity: 1830,
		age: 1,
		os: "iOS",
		certification: "VVSG 1.1 certified",
		scanRate: "59%",
		errorRate: "0.33%",
		reliability: "87%",
		qualityMeasure: "87%",
	},
	{
		provider: "Populex",
		model: "Slate",
		quantity: 1491,
		age: 5,
		os: "Microsoft Windows XP Tablet PC Edition",
		certification: "VVSG 2.0 certified",
		scanRate: "85%",
		errorRate: "1.75%",
		reliability: "88%",
		qualityMeasure: "87%",
	},
	{
		provider: "Premier Election Solutions (Diebold)",
		model: "AccuVote OS",
		quantity: 1736,
		age: 1,
		os: "Embedded Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "86%",
		errorRate: "0.95%",
		reliability: "81%",
		qualityMeasure: "85%",
	},
	{
		provider: "Premier Election Solutions (Diebold)",
		model: "AccuVote OSX",
		quantity: 577,
		age: 8,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "81%",
		errorRate: "0.99%",
		reliability: "80%",
		qualityMeasure: "85%",
	},
	{
		provider: "Sequoia Voting Systems",
		model: "AVC Advantage",
		quantity: 913,
		age: 3,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "55%",
		errorRate: "1.29%",
		reliability: "90%",
		qualityMeasure: "83%",
	},
	{
		provider: "Smartmatic/Los Angeles County",
		model: "VSAP BMD",
		quantity: 740,
		age: 7,
		os: "Embedded Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "59%",
		errorRate: "0.07%",
		reliability: "84%",
		qualityMeasure: "90%",
	},
	{
		provider: "Smartmatic/Los Angeles County",
		model: "VSAP Tally",
		quantity: 668,
		age: 7,
		os: "Embedded Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "54%",
		errorRate: "1.54%",
		reliability: "81%",
		qualityMeasure: "89%",
	},
	{
		provider: "Smartmatic/Los Angeles County",
		model: "VSAP Interactive Sample Ballot",
		quantity: 1103,
		age: 2,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "54%",
		errorRate: "1.65%",
		reliability: "82%",
		qualityMeasure: "86%",
	},
	{
		provider: "Tenex",
		model: "Precinct Central",
		quantity: 1265,
		age: 7,
		os: "iOS",
		certification: "VVSG 2.0 certified",
		scanRate: "97%",
		errorRate: "1.34%",
		reliability: "89%",
		qualityMeasure: "86%",
	},
	{
		provider: "Triad Governmental Systems",
		model: "Accessible Ballot Marking Tool (ABMT)",
		quantity: 2087,
		age: 8,
		os: "Web-based",
		certification: "VVSG 2.0 certified",
		scanRate: "100%",
		errorRate: "0.04%",
		reliability: "90%",
		qualityMeasure: "83%",
	},
	{
		provider: "Unisyn",
		model: "Freedom Vote Tablet (FVT)",
		quantity: 418,
		age: 9,
		os: "Linux",
		certification: "Not Certified",
		scanRate: "84%",
		errorRate: "0.35%",
		reliability: "86%",
		qualityMeasure: "86%",
	},
	{
		provider: "Unisyn",
		model: "OpenElect OVI",
		quantity: 1491,
		age: 10,
		os: "Linux",
		certification: "Not Certified",
		scanRate: "87%",
		errorRate: "0.68%",
		reliability: "84%",
		qualityMeasure: "85%",
	},
	{
		provider: "Unisyn",
		model: "OpenElect OVI-VC",
		quantity: 423,
		age: 6,
		os: "Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "92%",
		errorRate: "1.78%",
		reliability: "89%",
		qualityMeasure: "83%",
	},
	{
		provider: "Unisyn",
		model: "OpenElect OVCS",
		quantity: 670,
		age: 7,
		os: "Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "97%",
		errorRate: "1.02%",
		reliability: "88%",
		qualityMeasure: "88%",
	},
	{
		provider: "Unisyn",
		model: "Freedom Vote Scan (FVS)",
		quantity: 302,
		age: 5,
		os: "Linux",
		certification: "Not Certified",
		scanRate: "68%",
		errorRate: "0.71%",
		reliability: "90%",
		qualityMeasure: "82%",
	},
	{
		provider: "Unisyn",
		model: "OpenElect OVO",
		quantity: 1693,
		age: 6,
		os: "Linux",
		certification: "Not Certified",
		scanRate: "50%",
		errorRate: "0.33%",
		reliability: "89%",
		qualityMeasure: "90%",
	},
	{
		provider: "VR Systems",
		model: "EViD",
		quantity: 1748,
		age: 9,
		os: "Tablet / Mobile / COTS laptop",
		certification: "Not Certified",
		scanRate: "59%",
		errorRate: "1.72%",
		reliability: "90%",
		qualityMeasure: "85%",
	},
	{
		provider: "Voatz",
		model: "Mobile App",
		quantity: 773,
		age: 4,
		os: "Mobile App",
		certification: "VVSG 2.0 certified",
		scanRate: "56%",
		errorRate: "0.68%",
		reliability: "86%",
		qualityMeasure: "83%",
	},
	{
		provider: "Votem",
		model: "CastIron Voting Platform",
		quantity: 1332,
		age: 7,
		os: "Mobile Device",
		certification: "VVSG 1.0 certified",
		scanRate: "65%",
		errorRate: "0.64%",
		reliability: "81%",
		qualityMeasure: "86%",
	},
	{
		provider: "VotingWorks",
		model: "VxMark",
		quantity: 1238,
		age: 7,
		os: "Debian 12",
		certification: "VVSG 1.1 certified",
		scanRate: "59%",
		errorRate: "1.96%",
		reliability: "88%",
		qualityMeasure: "81%",
	},
	{
		provider: "VotingWorks",
		model: "VxCentralScan",
		quantity: 1802,
		age: 1,
		os: "Debian 12",
		certification: "VVSG 2.0 applied",
		scanRate: "93%",
		errorRate: "1.81%",
		reliability: "83%",
		qualityMeasure: "80%",
	},
	{
		provider: "VotingWorks",
		model: "VxScan",
		quantity: 2006,
		age: 9,
		os: "Debian 12",
		certification: "VVSG 1.0 certified",
		scanRate: "90%",
		errorRate: "0.25%",
		reliability: "81%",
		qualityMeasure: "86%",
	},
	{
		provider: "ES&S",
		model: "Model 650",
		quantity: 263,
		age: 10,
		os: "Windows",
		certification: "VVSG 2.0 applied",
		scanRate: "98%",
		errorRate: "0.04%",
		reliability: "85%",
		qualityMeasure: "82%",
	},
	{
		provider: "Clear Ballot",
		model: "ClearMark",
		quantity: 1519,
		age: 6,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "69%",
		errorRate: "0.92%",
		reliability: "85%",
		qualityMeasure: "83%",
	},
	{
		provider: "ES&S",
		model: "DS650",
		quantity: 876,
		age: 5,
		os: "Embedded OS",
		certification: "VVSG 1.1 certified",
		scanRate: "94%",
		errorRate: "1.55%",
		reliability: "82%",
		qualityMeasure: "88%",
	},
	{
		provider: "ES&S",
		model: "Model 150",
		quantity: 1383,
		age: 5,
		os: "Embedded OS",
		certification: "Not Certified",
		scanRate: "64%",
		errorRate: "1.69%",
		reliability: "81%",
		qualityMeasure: "82%",
	},
	{
		provider: "ES&S",
		model: "Model 550",
		quantity: 562,
		age: 8,
		os: "Embedded OS",
		certification: "Not Certified",
		scanRate: "88%",
		errorRate: "0.56%",
		reliability: "87%",
		qualityMeasure: "87%",
	},
	{
		provider: "ES&S/Unisyn",
		model: "InkaVote",
		quantity: 408,
		age: 1,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "70%",
		errorRate: "1.35%",
		reliability: "87%",
		qualityMeasure: "87%",
	},
	{
		provider: "In-House",
		model: "In-House Electronic Poll Books",
		quantity: 327,
		age: 3,
		os: "windows/android",
		certification: "Not Certified",
		scanRate: "83%",
		errorRate: "0.11%",
		reliability: "88%",
		qualityMeasure: "80%",
	},
	{
		provider: "ES&S",
		model: "DS950",
		quantity: 1076,
		age: 9,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "86%",
		errorRate: "0.87%",
		reliability: "89%",
		qualityMeasure: "88%",
	},
	{
		provider: "ES&S",
		model: "DS450",
		quantity: 695,
		age: 4,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "81%",
		errorRate: "0.84%",
		reliability: "86%",
		qualityMeasure: "84%",
	},
	{
		provider: "ES&S",
		model: "ExpressVote",
		quantity: 403,
		age: 4,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "82%",
		errorRate: "1.17%",
		reliability: "82%",
		qualityMeasure: "85%",
	},
	{
		provider: "ES&S",
		model: "ExpressVote XL",
		quantity: 799,
		age: 4,
		os: "Embedded Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "84%",
		errorRate: "0.35%",
		reliability: "81%",
		qualityMeasure: "84%",
	},
	{
		provider: "AVS",
		model: "WINVote",
		quantity: 2045,
		age: 2,
		os: "Windows 2000 Professional / Windows XP Embedded",
		certification: "VVSG 1.1 certified",
		scanRate: "82%",
		errorRate: "0.46%",
		reliability: "89%",
		qualityMeasure: "82%",
	},
	{
		provider: "Avante",
		model: "Vote-Trakker",
		quantity: 1412,
		age: 10,
		os: "Windows 2000 Professional",
		certification: "VVSG 2.0 applied",
		scanRate: "82%",
		errorRate: "0.55%",
		reliability: "85%",
		qualityMeasure: "81%",
	},
	{
		provider: "AVS",
		model: "WINScan",
		quantity: 318,
		age: 6,
		os: "Embedded Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "75%",
		errorRate: "0.54%",
		reliability: "89%",
		qualityMeasure: "83%",
	},
	{
		provider: "Clear Ballot",
		model: "ClearCast Go",
		quantity: 1980,
		age: 9,
		os: "Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "98%",
		errorRate: "1.58%",
		reliability: "87%",
		qualityMeasure: "88%",
	},
	{
		provider: "DFM Associates",
		model: "Mark-A-Vote",
		quantity: 224,
		age: 2,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "94%",
		errorRate: "0.98%",
		reliability: "81%",
		qualityMeasure: "86%",
	},
	{
		provider: "DFM Associates",
		model: "EIMS",
		quantity: 1181,
		age: 4,
		os: "Windows",
		certification: "VVSG 2.0 certified",
		scanRate: "99%",
		errorRate: "0.41%",
		reliability: "84%",
		qualityMeasure: "86%",
	},
	{
		provider: "DFM Associates",
		model: "Vote Center App",
		quantity: 339,
		age: 3,
		os: "Windows",
		certification: "VVSG 2.0 applied",
		scanRate: "80%",
		errorRate: "1.12%",
		reliability: "88%",
		qualityMeasure: "80%",
	},
	{
		provider: "Danaher",
		model: "Shouptronic 1242",
		quantity: 1754,
		age: 6,
		os: "Embedded DOS",
		certification: "VVSG 1.1 certified",
		scanRate: "96%",
		errorRate: "1.41%",
		reliability: "84%",
		qualityMeasure: "80%",
	},
	{
		provider: "DemTech",
		model: "Advocate Precinct",
		quantity: 662,
		age: 8,
		os: "Windows 10",
		certification: "Not Certified",
		scanRate: "81%",
		errorRate: "1.17%",
		reliability: "83%",
		qualityMeasure: "82%",
	},
	{
		provider: "DemTech",
		model: "ePollTAB",
		quantity: 1323,
		age: 3,
		os: "Windows 10",
		certification: "VVSG 1.0 certified",
		scanRate: "66%",
		errorRate: "1.48%",
		reliability: "80%",
		qualityMeasure: "83%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Precinct BMD",
		quantity: 1962,
		age: 8,
		os: "Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "78%",
		errorRate: "0.36%",
		reliability: "84%",
		qualityMeasure: "89%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Central",
		quantity: 750,
		age: 6,
		os: "Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "73%",
		errorRate: "1.30%",
		reliability: "88%",
		qualityMeasure: "86%",
	},
	{
		provider: "Dominion",
		model: "ImageCast X as DRE",
		quantity: 765,
		age: 3,
		os: "Android",
		certification: "VVSG 2.0 applied",
		scanRate: "74%",
		errorRate: "1.52%",
		reliability: "82%",
		qualityMeasure: "88%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Precinct",
		quantity: 2046,
		age: 2,
		os: "Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "51%",
		errorRate: "0.55%",
		reliability: "89%",
		qualityMeasure: "89%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Evolution",
		quantity: 1100,
		age: 10,
		os: "Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "57%",
		errorRate: "1.40%",
		reliability: "84%",
		qualityMeasure: "86%",
	},
	{
		provider: "Dominion",
		model: "ImageCast Precinct ATI",
		quantity: 2005,
		age: 1,
		os: "Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "68%",
		errorRate: "0.59%",
		reliability: "88%",
		qualityMeasure: "87%",
	},
	{
		provider: "Hart InterCivic",
		model: "Verity Duo",
		quantity: 648,
		age: 4,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "56%",
		errorRate: "1.68%",
		reliability: "82%",
		qualityMeasure: "82%",
	},
	{
		provider: "Hart InterCivic",
		model: "Verity Touch Writer",
		quantity: 1901,
		age: 9,
		os: "Proprietary Embedded OS",
		certification: "VVSG 1.0 certified",
		scanRate: "59%",
		errorRate: "1.41%",
		reliability: "83%",
		qualityMeasure: "90%",
	},
	{
		provider: "Hart InterCivic",
		model: "Ballot Now",
		quantity: 255,
		age: 9,
		os: "Proprietary Embedded OS",
		certification: "VVSG 1.1 certified",
		scanRate: "58%",
		errorRate: "0.62%",
		reliability: "87%",
		qualityMeasure: "88%",
	},
	{
		provider: "Hart InterCivic",
		model: "Verity Central",
		quantity: 448,
		age: 9,
		os: "Windows XP",
		certification: "Not Certified",
		scanRate: "66%",
		errorRate: "0.17%",
		reliability: "84%",
		qualityMeasure: "89%",
	},
	{
		provider: "Hart InterCivic",
		model: "eSlate",
		quantity: 1529,
		age: 4,
		os: "Windows 10",
		certification: "VVSG 1.1 certified",
		scanRate: "82%",
		errorRate: "1.07%",
		reliability: "89%",
		qualityMeasure: "83%",
	},
	{
		provider: "Hart InterCivic",
		model: "Verity Touch",
		quantity: 329,
		age: 4,
		os: "Proprietary Embedded OS",
		certification: "Not Certified",
		scanRate: "56%",
		errorRate: "1.47%",
		reliability: "90%",
		qualityMeasure: "83%",
	},
	{
		provider: "Hart InterCivic",
		model: "Verity Scan",
		quantity: 2053,
		age: 1,
		os: "Proprietary Embedded OS",
		certification: "VVSG 2.0 certified",
		scanRate: "95%",
		errorRate: "1.99%",
		reliability: "88%",
		qualityMeasure: "81%",
	},
	{
		provider: "Hart InterCivic",
		model: "eScan",
		quantity: 389,
		age: 1,
		os: "Proprietary Embedded OS",
		certification: "VVSG 1.1 certified",
		scanRate: "85%",
		errorRate: "0.58%",
		reliability: "82%",
		qualityMeasure: "85%",
	},
	{
		provider: "Hart InterCivic",
		model: "eScan A/T",
		quantity: 875,
		age: 4,
		os: "Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "73%",
		errorRate: "1.64%",
		reliability: "85%",
		qualityMeasure: "86%",
	},
	{
		provider: "IVS",
		model: "Inspire Ballot Marking Device",
		quantity: 1058,
		age: 8,
		os: "Linux",
		certification: "Not Certified",
		scanRate: "94%",
		errorRate: "0.43%",
		reliability: "83%",
		qualityMeasure: "82%",
	},
	{
		provider: "Democracy Live",
		model: "OmniBallot Tablet",
		quantity: 647,
		age: 5,
		os: "Windows 10 IoT Enterprise",
		certification: "VVSG 1.1 certified",
		scanRate: "54%",
		errorRate: "0.30%",
		reliability: "89%",
		qualityMeasure: "86%",
	},
	{
		provider: "Democracy Live",
		model: "OmniBallot Online",
		quantity: 2054,
		age: 8,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "61%",
		errorRate: "0.36%",
		reliability: "86%",
		qualityMeasure: "81%",
	},
	{
		provider: "Democracy Live",
		model: "Secure Select",
		quantity: 2161,
		age: 9,
		os: "Web-based",
		certification: "VVSG 2.0 applied",
		scanRate: "80%",
		errorRate: "0.84%",
		reliability: "80%",
		qualityMeasure: "86%",
	},
	{
		provider: "Dominion",
		model: "ImageCast X",
		quantity: 1325,
		age: 1,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "70%",
		errorRate: "1.42%",
		reliability: "86%",
		qualityMeasure: "88%",
	},
	{
		provider: "ES&S",
		model: "ExpressTouch",
		quantity: 1514,
		age: 10,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "83%",
		errorRate: "1.03%",
		reliability: "88%",
		qualityMeasure: "89%",
	},
	{
		provider: "ES&S",
		model: "AutoMARK",
		quantity: 2021,
		age: 8,
		os: "Windows",
		certification: "Not Certified",
		scanRate: "100%",
		errorRate: "0.78%",
		reliability: "88%",
		qualityMeasure: "83%",
	},
	{
		provider: "ES&S",
		model: "Batch-Fed Optical Scanner",
		quantity: 2028,
		age: 10,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "96%",
		errorRate: "1.63%",
		reliability: "84%",
		qualityMeasure: "81%",
	},
	{
		provider: "ES&S",
		model: "DS200",
		quantity: 1653,
		age: 3,
		os: "Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "87%",
		errorRate: "0.83%",
		reliability: "81%",
		qualityMeasure: "83%",
	},
	{
		provider: "ES&S",
		model: "DS300",
		quantity: 929,
		age: 9,
		os: "Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "96%",
		errorRate: "1.62%",
		reliability: "82%",
		qualityMeasure: "85%",
	},
	{
		provider: "ES&S/Unisyn",
		model: "InkaVote Plus",
		quantity: 720,
		age: 8,
		os: "Embedded Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "66%",
		errorRate: "0.56%",
		reliability: "84%",
		qualityMeasure: "87%",
	},
	{
		provider: "Enhanced Voting",
		model: "MyBallot",
		quantity: 1267,
		age: 8,
		os: "Web-based (single HTML file)",
		certification: "VVSG 2.0 applied",
		scanRate: "88%",
		errorRate: "0.66%",
		reliability: "88%",
		qualityMeasure: "90%",
	},
	{
		provider: "Five Cedars Group",
		model: "Alternate Format Ballot",
		quantity: 2038,
		age: 6,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "73%",
		errorRate: "1.58%",
		reliability: "80%",
		qualityMeasure: "80%",
	},
	{
		provider: "Hand Count",
		model: "Hand Counted Paper Ballots",
		quantity: 547,
		age: 3,
		os: "Embedded Linux",
		certification: "VVSG 1.0 certified",
		scanRate: "87%",
		errorRate: "1.95%",
		reliability: "82%",
		qualityMeasure: "81%",
	},
	{
		provider: "In-House",
		model: "In-House Internet Voting Systems",
		quantity: 2193,
		age: 10,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "100%",
		errorRate: "1.48%",
		reliability: "82%",
		qualityMeasure: "89%",
	},
	{
		provider: "In-House",
		model: "In-House Remote Ballot Marking Systems",
		quantity: 1901,
		age: 7,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "81%",
		errorRate: "0.54%",
		reliability: "88%",
		qualityMeasure: "81%",
	},
	{
		provider: "MicroVote",
		model: "MV-464",
		quantity: 1574,
		age: 3,
		os: "Embedded Linux",
		certification: "VVSG 2.0 applied",
		scanRate: "95%",
		errorRate: "0.88%",
		reliability: "86%",
		qualityMeasure: "87%",
	},
	{
		provider: "MicroVote/Chatsworth",
		model: "ACP 2200",
		quantity: 2066,
		age: 4,
		os: "Embedded OS",
		certification: "VVSG 2.0 certified",
		scanRate: "81%",
		errorRate: "1.35%",
		reliability: "84%",
		qualityMeasure: "86%",
	},
	{
		provider: "Premier Election Solutions (Diebold)",
		model: "AccuVote OS Central",
		quantity: 1649,
		age: 5,
		os: "Proprietary embedded OS",
		certification: "Not Certified",
		scanRate: "63%",
		errorRate: "0.00%",
		reliability: "82%",
		qualityMeasure: "87%",
	},
	{
		provider: "Premier Election Solutions (Diebold)",
		model: "AccuVote TSX",
		quantity: 1513,
		age: 7,
		os: "Windows CE 4.1",
		certification: "VVSG 2.0 certified",
		scanRate: "71%",
		errorRate: "1.53%",
		reliability: "86%",
		qualityMeasure: "89%",
	},
	{
		provider: "Robis",
		model: "AskED ePollbook",
		quantity: 2104,
		age: 8,
		os: "Windows 10 Pro",
		certification: "VVSG 2.0 certified",
		scanRate: "65%",
		errorRate: "0.91%",
		reliability: "89%",
		qualityMeasure: "86%",
	},
	{
		provider: "Sequoia Voting Systems",
		model: "Optech 400C",
		quantity: 2128,
		age: 1,
		os: "Proprietary embedded OS",
		certification: "VVSG 2.0 certified",
		scanRate: "84%",
		errorRate: "1.03%",
		reliability: "84%",
		qualityMeasure: "84%",
	},
	{
		provider: "Sequoia Voting Systems",
		model: "AVC Edge",
		quantity: 1845,
		age: 10,
		os: "Proprietary embedded OS",
		certification: "VVSG 1.1 certified",
		scanRate: "71%",
		errorRate: "1.25%",
		reliability: "83%",
		qualityMeasure: "88%",
	},
	{
		provider: "Sequoia Voting Systems",
		model: "Optech Insight",
		quantity: 1533,
		age: 1,
		os: "Proprietary embedded OS",
		certification: "VVSG 1.0 certified",
		scanRate: "97%",
		errorRate: "0.94%",
		reliability: "87%",
		qualityMeasure: "88%",
	},
	{
		provider: "Sequoia and ES&S",
		model: "Optech IIIP-Eagle",
		quantity: 2149,
		age: 3,
		os: "Proprietary embedded OS",
		certification: "VVSG 1.1 certified",
		scanRate: "90%",
		errorRate: "1.09%",
		reliability: "86%",
		qualityMeasure: "80%",
	},
	{
		provider: "UniLect",
		model: "Patriot",
		quantity: 262,
		age: 4,
		os: "Embedded Linux",
		certification: "VVSG 2.0 certified",
		scanRate: "64%",
		errorRate: "0.56%",
		reliability: "84%",
		qualityMeasure: "84%",
	},
	{
		provider: "UniLect",
		model: "Marksense Scanner",
		quantity: 2152,
		age: 2,
		os: "Embedded Linux",
		certification: "Not Certified",
		scanRate: "73%",
		errorRate: "0.35%",
		reliability: "89%",
		qualityMeasure: "88%",
	},
	{
		provider: "Vote-PAD",
		model: "Ballot Marking System",
		quantity: 468,
		age: 9,
		os: "Embedded Linux",
		certification: "VVSG 1.1 certified",
		scanRate: "51%",
		errorRate: "0.23%",
		reliability: "83%",
		qualityMeasure: "86%",
	},
	{
		provider: "Votec",
		model: "VoteSafe",
		quantity: 956,
		age: 3,
		os: "Windows",
		certification: "VVSG 2.0 certified",
		scanRate: "68%",
		errorRate: "1.36%",
		reliability: "81%",
		qualityMeasure: "82%",
	},
];

export default function EquipmentSummaryTable() {
	const [page, setPage] = useState(0);
	const [rowsPerPage, setRowsPerPage] = useState(3);

	const rows = [];
	for (let row of mockData) {
		rows.push({
			provider: row.provider,
			model: row.model,
			quantity: row.quantity,
			age: row.age,
			os: row.os,
			certification: row.certification,
			scanRate: row.scanRate,
			errorRate: row.errorRate,
			reliability: row.reliability,
			qualityMeasure: row.qualityMeasure,
		});
	}

	return (
		<Paper
			sx={{
				bgcolor: "background.default",
				color: "text.primary",
				height: "100%",
				display: "flex",
				flexDirection: "column",
				overflow: "hidden",
			}}>
			<Typography variant="subtitle1" sx={{ p: 2, pb: 1, fontWeight: 600 }}>
				U.S. Voting Equipment Summary (2024)
			</Typography>

			{/* Table section scrolls independently */}
			<Box sx={{ flex: 1, overflowY: "auto", overflowX: "auto" }}>
				<TableContainer sx={{ overflow: "visible" }}>
					<Table size="small" stickyHeader>
						<TableHead>
							<TableRow>
								<TableCell>Provider</TableCell>
								<TableCell>Model</TableCell>
								<TableCell>Quantity</TableCell>
								<TableCell>Age (yrs)</TableCell>
								<TableCell>OS</TableCell>
								<TableCell>Certification</TableCell>
								<TableCell>Scan Rate</TableCell>
								<TableCell>Error Rate</TableCell>
								<TableCell>Reliability</TableCell>
								<TableCell>Quality Measure</TableCell>
							</TableRow>
						</TableHead>
						<TableBody>
							{rows.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage).map((r, i) => (
								<TableRow key={i}>
									<TableCell>{r.provider}</TableCell>
									<TableCell>{r.model}</TableCell>
									<TableCell align="right">{r.quantity}</TableCell>
									<TableCell align="right">{r.age}</TableCell>
									<TableCell>{r.os}</TableCell>
									<TableCell>{r.certification}</TableCell>
									<TableCell align="right">{r.scanRate}</TableCell>
									<TableCell align="right">{r.errorRate}</TableCell>
									<TableCell align="right">{r.reliability}</TableCell>
									<TableCell align="right">{r.qualityMeasure}</TableCell>
								</TableRow>
							))}
						</TableBody>
					</Table>
				</TableContainer>
			</Box>

			<Box sx={{ flexShrink: 0 }}>
				<TablePagination
					component="div"
					count={rows.length}
					page={page}
					onPageChange={(_, p) => setPage(p)}
					rowsPerPage={rowsPerPage}
					onRowsPerPageChange={(e) => {
						setRowsPerPage(parseInt(e.target.value, 10));
						setPage(0);
					}}
					rowsPerPageOptions={[3, 5, 10]}
					sx={{ borderTop: "1px solid rgba(255,255,255,0.1)" }}
				/>
			</Box>
		</Paper>
	);
}
